stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm install --prefix client
    - npm install --prefix server
    # start the server in the background
    - npm run server
    - npm run client
    # run Cypress tests
    - npm run test