version: '2'

services:
  server1:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mocompres/devops_server"
  
  server2:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mocompres/devops_server"
  


  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mocompres/devops_client"

  nginxserver:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/ssl/
      - /home/deploy/logs/:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
  
  