version: '2'

services:
  server-prime:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mocompres/devops_server"

  server-second: 
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mocompres/devops_server"
  
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mocompres/devops_client"

  nginxserver:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  