version: '2'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mocompres/devops_server"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mocompres/devops_client"

  nginxserver:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: "mocompres/nginx_proxy"
    ports:
      - "80:80"
  